/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket;

import javax.swing.JOptionPane;

/**
 *
 * @author Pepita Neysa
 */
public class TiketFilm extends javax.swing.JFrame {

    panel_infor p1;
    panel_sinop p2;
    
    /**
     * Creates new form TiketFilm
     */
    public TiketFilm() {
        initComponents();
        setLocationRelativeTo(this);
        
        p1 = new panel_infor();
        p2 = new panel_sinop();

        panel_utama.add(p1);
        panel_utama.add(p2);

        p1.setVisible(false);
        p2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        infor = new javax.swing.JButton();
        panel_utama = new javax.swing.JPanel();
        sinopsis = new javax.swing.JButton();
        panell = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        j1 = new javax.swing.JRadioButton();
        j4 = new javax.swing.JRadioButton();
        j3 = new javax.swing.JRadioButton();
        j2 = new javax.swing.JRadioButton();
        pesan1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        reg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regu = new javax.swing.JComboBox<>();
        premm = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tot = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Sin\\KOLEAH\\IMK\\IMK\\src\\Tiket\\img\\Webp.net-resizeimage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 167, 250);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("AVENGER : END GAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 20, 251, 20);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("R13+");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 50, 34, 33);

        jLabel4.setText("180 Menit");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 90, 72, 14);

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Sin\\KOLEAH\\IMK\\IMK\\src\\Tiket\\img\\Webp.net-resizeimage (4).png")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(210, 90, 15, 15);

        infor.setText("Informasi Film");
        infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inforActionPerformed(evt);
            }
        });
        jPanel1.add(infor);
        infor.setBounds(300, 120, 120, 23);

        panel_utama.setBackground(new java.awt.Color(153, 204, 255));
        panel_utama.setLayout(new javax.swing.BoxLayout(panel_utama, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(panel_utama);
        panel_utama.setBounds(440, 20, 270, 260);

        sinopsis.setText("Sinopsis");
        sinopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinopsisActionPerformed(evt);
            }
        });
        jPanel1.add(sinopsis);
        sinopsis.setBounds(210, 120, 80, 23);

        panell.setBackground(new java.awt.Color(153, 204, 255));
        panell.setLayout(new javax.swing.BoxLayout(panell, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(panell);
        panell.setBounds(430, 300, 0, 0);

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("2D");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 50, 34, 33);

        buttonGroup2.add(j1);
        j1.setText("10.30");
        jPanel1.add(j1);
        j1.setBounds(210, 180, 60, 23);

        buttonGroup2.add(j4);
        j4.setText("21.00");
        jPanel1.add(j4);
        j4.setBounds(210, 220, 60, 23);

        buttonGroup2.add(j3);
        j3.setText("17.30");
        jPanel1.add(j3);
        j3.setBounds(350, 180, 60, 23);

        buttonGroup2.add(j2);
        j2.setText("14.00");
        jPanel1.add(j2);
        j2.setBounds(280, 180, 60, 23);

        pesan1.setText("Detail Pesanan");
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });
        jPanel1.add(pesan1);
        pesan1.setBounds(130, 470, 130, 23);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Silahkan pilih jenis  tiket");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 290, 170, 20);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(440, 290, 280, 100);

        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiket/img/reg.png"))); // NOI18N
        jPanel1.add(reg);
        reg.setBounds(40, 320, 130, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiket/img/prem.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 320, 130, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Black (regular)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 390, 90, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Gold (premium)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 390, 120, 15);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("Silahkan pilih jam tayang ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 154, 170, 20);

        regu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel1.add(regu);
        regu.setBounds(40, 410, 130, 20);

        premm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel1.add(premm);
        premm.setBounds(220, 410, 130, 20);

        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 400, 61, 23);
        jPanel1.add(tot);
        tot.setBounds(440, 440, 280, 30);

        jButton2.setText("Selesai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 490, 90, 23);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 754, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void sinopsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinopsisActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_sinopsisActionPerformed

    private void inforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inforActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_inforActionPerformed

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
        // TODO add your handling code here:
        String jam = " ";
        String regular = regu.getSelectedItem().toString();
        String premium = premm.getSelectedItem().toString();
        
        //regular
        if(regu.getSelectedItem()== "0"){
        }
        if(regu.getSelectedItem()== "1"){
        }
        if(regu.getSelectedItem()== "2"){
        }
        if(regu.getSelectedItem()== "3"){
        }
        if(regu.getSelectedItem()== "4"){
        }
        if(regu.getSelectedItem()== "5"){
        }
        //premium
        if(premm.getSelectedItem()== "0"){
        }
        if(premm.getSelectedItem()== "1"){
        }
        if(premm.getSelectedItem()== "2"){
        }
        if(premm.getSelectedItem()== "3"){
        }
        if(premm.getSelectedItem()== "4"){
        }
        if(premm.getSelectedItem()== "5"){
        }
        //jam
        if (j1.isSelected())
            jam = "10.30";
        else if (j2.isSelected())
            jam = "14.00";
        else if (j3.isSelected())
            jam = "17.30";
        else if (j4.isSelected())
            jam = "21.00";
        
        ta.setText("Jam tayang yang anda pilih : "+jam+
                "\n"+"Tiket Regular yang anda beli : "+regular+"\n"+
                "Tiket Premium yang anda beli : "+premium);
    }//GEN-LAST:event_pesan1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rg = Integer.parseInt(regu.getSelectedItem().toString());
        int hasil = rg*25000;
        int pr = Integer.parseInt(premm.getSelectedItem().toString());
        int hasil2 = pr*50000;
        int total = hasil+hasil2;
        tot.setText("Total pembayaran :"+total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Terima kasih, Jangan lupa bayar ya!"," ",JOptionPane.WARNING_MESSAGE);
            System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton infor;
    private javax.swing.JRadioButton j1;
    private javax.swing.JRadioButton j2;
    private javax.swing.JRadioButton j3;
    private javax.swing.JRadioButton j4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel panell;
    private javax.swing.JButton pesan1;
    private javax.swing.JComboBox<String> premm;
    private javax.swing.JLabel reg;
    private javax.swing.JComboBox<String> regu;
    private javax.swing.JButton sinopsis;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
